### ISSUE TITLE
Version Incompatibility with Latest Nix

### ISSUE THREAD

**Issue by naftulikay** [tailhook/signal#10]
Presently, if I use a later version of `nix` (e.g. `0.14`) and try to use `signal`, I get failed compilations due to what seems to be a breaking `nix` API change. Would it be possible to update `signal` to use the latest `nix`? This forces me to use a version of `nix` that is outdated.

**Comment by tailhook** [comment]
Released `v0.7.0`. (Unfortunately, nix is public dependency so every breaking release of nix == breaking release of signal)

**Comment by naftulikay** [comment]
You may be able to prevent future breakage by building a public wrapper around the nix types.
